export const UPDATE_CHILDREN = "UPDATE_CHILDREN";
export const REMOVE_CHILD = "DELETE_CHILD";
export const UPDATE_CHORES = "UPDATE_CHORES";
export const REMOVE_CHORE = "DELETE_CHORE";
export const SET_CURRENT_CHILD = "SET_CURRENT_CHILD"
export const LOAD_CHORES = "LOAD_CHORES"